version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/extensions_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/extensions_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads  # Persistent file storage

volumes:
  pg_data: